[ChannelsImporter] fix TypeError
Traceback (most recent call last):
  File "/var/volatile/tmp/./w.py", line 10, in forceSaveEPGonRemoteReceiver
    print("[ChannelsImporter][saveEPGonRemoteReceiver] Response: %d, %s" % (response.getcode(), response.read().strip().replace("\r", "").replace("\n", "")))
                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'