[config.py] Revert ConfigSet code. This was tested and working fine on Zgemma but causes a boot loop on Vu+ Ultimo 4K
<   398.7125> VideoWizard has_dvi False
<   398.7126> VideoWizard has_rca False
<   398.7127> VideoWizard has_jack False
<   398.7128> VideoWizard has_scart False
<   398.7128> AVSwitch Scart-YPbPr False
<   398.7129> AVSwitch no_YPbPr True
<   398.7130> AVSwitch yellow_RCA_no_scart False
<   398.7131> AVSwitch no_yellow_RCA__no_scart True
[MAIN] executing main
<   398.7325> Traceback (most recent call last):
<   398.7326>   File "/usr/lib/enigma2/python/mytest.py", line 40, in <module>
<   398.7327>     from Screens import InfoBar
<   398.7327>   File "/usr/lib/enigma2/python/Screens/InfoBar.py", line 5, in <module>
<   398.7328>   File "/usr/lib/enigma2/python/Screens/MovieSelection.py", line 52, in <module>
<   398.7329>   File "/usr/lib/enigma2/python/Components/config.py", line 1944, in __setattr__
<   398.7330>   File "/usr/lib/enigma2/python/Components/config.py", line 1617, in load
<   398.7332> AttributeError: 'NoneType' object has no attribute 'sort'
<   398.7341> [eDVBDB] ---- saving lame channel db
<   398.7504> [eDVBDB] saved 166 channels and 1650 services!