[ButtonSetup] fix BSoD
Based on https://github.com/OpenPLi/enigma2/commit/6363bd421f82a0b11145996e8dc3e1cbce7679e1

-required for some menu calls

More info:
Green Screen with PiP and Tuner Configuration (when Tuner Configuration is selected with hotkey!)
I have put Tuner Configuration on a hotkey (together with Signal Finder, Positioner Setup, various "Scans", ...).
When I have PiP running, then select Tuner Configuration (from the hotkey!), then change the tuner config, then press Green Button on the remote to save, then I get a Green Screen.

Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 57, in action
  File "/usr/lib/enigma2/python/Screens/Satconfig.py", line 558, in keySave
  File "/usr/lib/enigma2/python/Screens/ServiceStopScreen.py", line 47, in stopService
AttributeError: 'NoneType' object has no attribute 'servicelist'

OpenPLi thread:
https://forums.openpli.org/topic/87322-bug-reports-and-feature-requests-for-pip/#entry1413722