font.cpp: Remove register keyword
Register keyword is deprecated since C++11 and fails to compile with C++17.
It's harmless to remove the keyword now for future update to GCC 11 (C++17 as default) and
requirement for libsigc++ 3.0.

See e.g:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4340

Error:

../../git/lib/gdi/font.cpp:1102:38: error: ISO C++17 does not allow 'register' storage class specifier [-Werror=register]
|  1102 |                         register int sx = sxbase;
|       |                                      ^~
| ../../git/lib/gdi/font.cpp:1131:54: error: ISO C++17 does not allow 'register' storage class specifier [-Werror=register]
|  1131 |                                         register int extra_buffer_stride = buffer_stride - sx;
|       |                                                      ^~~~~~~~~~~~~~~~~~~
| ../../git/lib/gdi/font.cpp:1132:56: error: ISO C++17 does not allow 'register' storage class specifier [-Werror=register]
|  1132 |                                         register __u8 *td=d;
|       |                                                        ^~